Experimenting with a "ref_only" option.

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -47,6 +47,7 @@ commit_verification_keys=$(jq -r '(.source.commit_verification_keys // [])[]' < 
 tag_filter=$(jq -r '.source.tag_filter // ""' < $payload)
 gpg_keyserver=$(jq -r '.source.gpg_keyserver // "hkp://ipv4.pool.sks-keyservers.net/"' < $payload)
 disable_git_lfs=$(jq -r '(.params.disable_git_lfs // false)' < $payload)
+commit_ref_only=$(jq -r '(debug | .params.ref_only // false)' < $payload)
 clean_tags=$(jq -r '(.params.clean_tags // false)' < $payload)
 short_ref_format=$(jq -r '(.params.short_ref_format // "%s")' < $payload)
 
@@ -78,22 +79,32 @@ if [ "$disable_git_lfs" == "true" ]; then
   export GIT_LFS_SKIP_SMUDGE=1
 fi
 
-git clone --single-branch $depthflag $uri $branchflag $destination $tagflag
-
-cd $destination
-
-git fetch origin refs/notes/*:refs/notes/* $tagflag
-
-if [ "$depth" -gt 0 ]; then
-  "$bin_dir"/deepen_shallow_clone_until_ref_is_found_then_check_out "$depth" "$ref" "$tagflag"
+if [ "$commit_ref_only" == "true" ]; then
+  mkdir $destination
+  if [ -n "$branch" ]; then
+	return_ref=$(git ls-remote $uri $branch | sed 's/\t.*//')
+  else
+	return_ref=$(git ls-remote $uri HEAD | sed 's/\t.*//')
+  fi
+  echo $return_ref > $destination/sha
+  metadata="\"\""
 else
-  git checkout -q "$ref"
-fi
+  git clone --single-branch $depthflag $uri $branchflag $destination $tagflag
 
-invalid_key() {
-  echo "Invalid GPG key in: ${commit_verification_keys}"
-  exit 2
-}
+  cd $destination
+
+  git fetch origin refs/notes/*:refs/notes/* $tagflag
+
+  if [ "$depth" -gt 0 ]; then
+    "$bin_dir"/deepen_shallow_clone_until_ref_is_found_then_check_out "$depth" "$ref" "$tagflag"
+  else
+    git checkout -q "$ref"
+  fi
+
+  invalid_key() {
+    echo "Invalid GPG key in: ${commit_verification_keys}"
+    exit 2
+  }
 
 commit_not_signed() {
   commit_id=$(git rev-parse ${ref})
@@ -108,93 +119,99 @@ if [ ! -z "${commit_verification_keys}" ] || [ ! -z "${commit_verification_key_i
   if [ ! -z "${commit_verification_key_ids}" ]; then
     echo "${commit_verification_key_ids}" | \
       xargs --no-run-if-empty -n1 gpg --batch --keyserver $gpg_keyserver --recv-keys
+        fi
+        git verify-commit $(git rev-list -n 1 $ref) || commit_not_signed
+      fi
+
+      git log -1 --oneline
+      git clean --force --force -d
+      git submodule sync
+
+      if [ -f $GIT_CRYPT_KEY_PATH ]; then
+        echo "unlocking git repo"
+        git-crypt unlock $GIT_CRYPT_KEY_PATH
+      fi
+
+
+      submodule_parameters=""
+      if [ "$submodule_remote" != "false" ]; then
+        submodule_parameters+=" --remote "
+      fi
+      if [ "$submodule_recursive" != "false" ]; then
+        submodule_parameters+=" --recursive "
+      fi
+
+      if [ "$submodules" != "none" ]; then
+        value_regexp="."
+        if [ "$submodules" != "all" ]; then
+          value_regexp="$(echo $submodules | jq -r 'map(. + "$") | join("|")')"
+        fi
+
+        {
+          git config --file .gitmodules --name-only --get-regexp '\.path$' "$value_regexp" |
+            sed -e 's/^submodule\.\(.\+\)\.path$/\1/'
+          } | while read submodule_name; do
+        submodule_path="$(git config --file .gitmodules --get "submodule.${submodule_name}.path")"
+
+        if [ "$depth" -gt 0 ]; then
+          git config "submodule.${submodule_name}.update" "!$bin_dir/deepen_shallow_clone_until_ref_is_found_then_check_out $depth"
+        fi
+
+        if ! [ -e "$submodule_path" ]; then
+          echo $'\e[31m'"warning: skipping missing submodule: $submodule_path"$'\e[0m'
+          continue
+        fi
+
+        git submodule update --init --no-fetch $depthflag $submodule_parameters "$submodule_path"
+
+        if [ "$depth" -gt 0 ]; then
+          git config --unset "submodule.${submodule_name}.update"
+        fi
+      done
+    fi
+
+    for branch in $fetch; do
+      git fetch origin $branch
+      git branch $branch FETCH_HEAD
+    done
+
+    if [ "$ref" == "HEAD" ]; then
+      return_ref=$(git rev-parse HEAD)
+    else
+      return_ref=$ref
+    fi
+
+  # Store committer email in .git/committer. Can be used to send email to last committer on failed build
+  # Using https://github.com/mdomke/concourse-email-resource for example
+  git --no-pager log -1 --pretty=format:"%ae" > .git/committer
+
+  # Store git-resource returned version ref .git/ref. Useful to know concourse
+  # pulled ref in following tasks and resources.
+  echo "${return_ref}" > .git/ref
+
+  # Store short ref with templating. Useful to build Docker images with
+  # a custom tag
+  echo "${return_ref}" | cut -c1-7 | awk "{ printf \"${short_ref_format}\", \$1 }" > .git/short_ref
+
+  # Store commit message in .git/commit_message. Can be used to inform about
+  # the content of a successfull build.
+  # Using https://github.com/cloudfoundry-community/slack-notification-resource
+  # for example
+  git log -1 --format=format:%B > .git/commit_message
+
+  metadata=$(git_metadata)
+
+  if [ "$clean_tags" == "true" ]; then
+    git tag | xargs git tag -d
   fi
-  git verify-commit $(git rev-list -n 1 $ref) || commit_not_signed
 fi
 
-git log -1 --oneline
-git clean --force --force -d
-git submodule sync
-
-if [ -f $GIT_CRYPT_KEY_PATH ]; then
-  echo "unlocking git repo"
-  git-crypt unlock $GIT_CRYPT_KEY_PATH
-fi
-
-
-submodule_parameters=""
-if [ "$submodule_remote" != "false" ]; then
-  submodule_parameters+=" --remote "
-fi
-if [ "$submodule_recursive" != "false" ]; then
-  submodule_parameters+=" --recursive "
-fi
-
-if [ "$submodules" != "none" ]; then
-  value_regexp="."
-  if [ "$submodules" != "all" ]; then
-    value_regexp="$(echo $submodules | jq -r 'map(. + "$") | join("|")')"
-  fi
-
-  {
-    git config --file .gitmodules --name-only --get-regexp '\.path$' "$value_regexp" |
-      sed -e 's/^submodule\.\(.\+\)\.path$/\1/'
-  } | while read submodule_name; do
-    submodule_path="$(git config --file .gitmodules --get "submodule.${submodule_name}.path")"
-
-    if [ "$depth" -gt 0 ]; then
-      git config "submodule.${submodule_name}.update" "!$bin_dir/deepen_shallow_clone_until_ref_is_found_then_check_out $depth"
-    fi
-
-    if ! [ -e "$submodule_path" ]; then
-      echo $'\e[31m'"warning: skipping missing submodule: $submodule_path"$'\e[0m'
-      continue
-    fi
-
-    git submodule update --init --no-fetch $depthflag $submodule_parameters "$submodule_path"
-
-    if [ "$depth" -gt 0 ]; then
-      git config --unset "submodule.${submodule_name}.update"
-    fi
-  done
-fi
-
-for branch in $fetch; do
-  git fetch origin $branch
-  git branch $branch FETCH_HEAD
-done
-
-if [ "$ref" == "HEAD" ]; then
-  return_ref=$(git rev-parse HEAD)
-else
-  return_ref=$ref
-fi
-
-# Store committer email in .git/committer. Can be used to send email to last committer on failed build
-# Using https://github.com/mdomke/concourse-email-resource for example
-git --no-pager log -1 --pretty=format:"%ae" > .git/committer
-
-# Store git-resource returned version ref .git/ref. Useful to know concourse
-# pulled ref in following tasks and resources.
-echo "${return_ref}" > .git/ref
-
-# Store short ref with templating. Useful to build Docker images with
-# a custom tag
-echo "${return_ref}" | cut -c1-7 | awk "{ printf \"${short_ref_format}\", \$1 }" > .git/short_ref
-
-# Store commit message in .git/commit_message. Can be used to inform about
-# the content of a successfull build.
-# Using https://github.com/cloudfoundry-community/slack-notification-resource
-# for example
-git log -1 --format=format:%B > .git/commit_message
-
-metadata=$(git_metadata)
-
-if [ "$clean_tags" == "true" ]; then
-  git tag | xargs git tag -d
-fi
+echo "{
+version: {ref: $(echo $return_ref | jq -R .)},
+metadata: $metadata
+}"
 
 jq -n "{
-  version: {ref: $(echo $return_ref | jq -R .)},
-  metadata: $metadata
+version: {ref: $(echo $return_ref | jq -R .)},
+metadata: $metadata
 }" >&3
